name: Upload Release

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          ref: beta
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 13.4
          cache: yarn
      - name: NPM or Yarn install with caching
        # You may pin to the exact commit or the version.
        # uses: bahmutov/npm-install@44b9e76df0949f3df6616b334af42e055ce24831
        uses: bahmutov/npm-install@v1.6.0
      - name: Build app
        run: |
          npm run pack
      - name: Zip release
        uses: TheDoctor0/zip-release@0.6.0
        with:
          filename: "ice-spear-${{ steps.get_version.outputs.VERSION }}.zip"
          path: ./dist/win-unpacked
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ice-spear-${{ steps.get_version.outputs.VERSION }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
